const questionPool = [
  { question: "Caminamos ___ el parque para disfrutar el buen clima.", correct: "por", rationale: "Por is used for movement through or along a space, such as a park. It describes the route taken." },
  { question: "Este regalo es ___ mi mejor amigo.", correct: "para", rationale: "Para is used to indicate the recipient of something, in this case, the gift is for the best friend." },
  { question: "Gracias ___ tu ayuda con el proyecto.", correct: "por", rationale: "Por is used to express gratitude or the reason for an action. The speaker is thanking someone for their help." },
  { question: "Estuve en casa ___ el mal tiempo.", correct: "por", rationale: "Por is used to indicate the cause or reason. The speaker stayed home because of the bad weather." },
  { question: "Salimos ___ la playa a las 8 de la mañana.", correct: "para", rationale: "Para is used to indicate the destination. The speaker is saying they are leaving for the beach." },
  { question: "Trabajé toda la noche ___ terminar el informe a tiempo.", correct: "para", rationale: "Para is used to express the purpose or goal of an action. The speaker worked to finish the report." },
  { question: "¿Puedes trabajar ___ mí mañana? Estoy muy ocupado.", correct: "por", rationale: "Por is used to indicate substitution. The speaker is asking someone to work on their behalf." },
  { question: "Lo compré ___ $50 en una tienda cercana.", correct: "por", rationale: "Por is used to indicate exchange. The speaker traded money ($50) for an item." },
  { question: "Ella viajó ___ España durante las vacaciones de verano.", correct: "por", rationale: "Por is used to describe movement through a place. The speaker says the person traveled through Spain." },
  { question: "Este tren va ___ Madrid y hace pocas paradas.", correct: "para", rationale: "Para is used to indicate the destination. The train is going to Madrid." },
  { question: "Viajamos ___ avión porque era más rápido que el tren.", correct: "por", rationale: "Por is used to indicate the means of transportation. The speaker traveled by plane." },
  { question: "Este medicamento es ___ aliviar el dolor rápidamente.", correct: "para", rationale: "Para is used to express purpose or goal. The medicine is to relieve pain." },
  { question: "Pasé ___ tu casa, pero no estabas.", correct: "por", rationale: "Por is used to describe movement along or past a place. The speaker passed by someone's house." },
  { question: "El proyecto es muy importante ___ mi carrera profesional.", correct: "para", rationale: "Para is used to express purpose or benefit. The project is important for the speaker's career." },
  { question: "Estudié toda la noche ___ sacar una buena nota en el examen.", correct: "para", rationale: "Para is used to express purpose or goal. The speaker studied to get a good grade." },
  { question: "Nos quedamos en casa ___ la tormenta.", correct: "por", rationale: "Por is used to indicate the cause or reason. The speaker stayed home because of the storm." },
  { question: "Pagué demasiado dinero ___ estas entradas al concierto.", correct: "por", rationale: "Por is used to indicate exchange. The speaker traded money for concert tickets." },
  { question: "Él es muy inteligente ___ su edad.", correct: "para", rationale: "Para is used to make a comparison or show a standard. The speaker compares his intelligence to his age." },
  { question: "El autobús sale ___ el aeropuerto en cinco minutos.", correct: "para", rationale: "Para is used to indicate the destination. The bus is going to the airport." },
  { question: "Estoy aquí ___ ayudarte con cualquier cosa que necesites.", correct: "para", rationale: "Para is used to express purpose. The speaker is here to help someone." },
  { question: "Lo hice ___ amor, no por dinero.", correct: "por", rationale: "Por is used to express the reason or cause of the action. The speaker did it out of love." },
  { question: "Caminamos ___ el bosque durante nuestra excursión.", correct: "por", rationale: "Por is used for movement through a space. The speaker walked through the forest." },
  { question: "Este documento es ___ entregar mañana al profesor.", correct: "para", rationale: "Para is used to express a deadline. The document must be delivered by tomorrow." },
  { question: "Ella fue premiada ___ su dedicación y esfuerzo en el trabajo.", correct: "por", rationale: "Por is used to indicate the reason. The speaker says she was rewarded because of her dedication." },
  { question: "Caminamos ___ debajo del puente para evitar el sol directo.", correct: "por", rationale: "Por is used to indicate movement through or along. The speaker walked under the bridge." },
  { question: "Necesitamos terminar este trabajo ___ la próxima semana.", correct: "para", rationale: "Para is used to express a deadline. The work must be finished by next week." },
  { question: "Fui al mercado ___ comprar frutas frescas.", correct: "para", rationale: "Para is used to express purpose. The speaker went to the market to buy fresh fruit." },
  { question: "Gracias ___ venir a mi fiesta de cumpleaños.", correct: "por", rationale: "Por is used to express gratitude or the reason for the action. The speaker is thanking someone for coming to their party." },
  { question: "Estudiamos mucho ___ pasar el examen final de química.", correct: "para", rationale: "Para is used to express purpose. The speaker studied to pass the exam." },
  { question: "Este libro es ___ aprender más sobre historia mundial.", correct: "para", rationale: "Para is used to express purpose or goal. The book is to learn more about world history." }
];
